/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: leveldbwrapperlib.i

package leveldbwrapperlib

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


typedef _gostring_ swig_type_1;
typedef _gostring_ swig_type_2;
typedef _gostring_ swig_type_3;
typedef _gostring_ swig_type_4;
extern void _wrap_Swig_free_leveldbwrapperlib_ccc61ccd5094785b(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_leveldbwrapperlib_ccc61ccd5094785b(swig_intgo arg1);
extern uintptr_t _wrap_new_LevelDBInterface_leveldbwrapperlib_ccc61ccd5094785b(void);
extern void _wrap_delete_LevelDBInterface_leveldbwrapperlib_ccc61ccd5094785b(uintptr_t arg1);
extern void _wrap_LevelDBInterface_Put_leveldbwrapperlib_ccc61ccd5094785b(uintptr_t arg1, swig_type_1 arg2, swig_type_2 arg3);
extern swig_type_3 _wrap_LevelDBInterface_Get_leveldbwrapperlib_ccc61ccd5094785b(uintptr_t arg1, swig_type_4 arg2);
#undef intgo

#cgo LDFLAGS: -lleveldb
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


type _ sync.Mutex


type swig_gostring struct { p uintptr; n int }
func swigCopyString(s string) string {
  p := *(*swig_gostring)(unsafe.Pointer(&s))
  r := string((*[0x7fffffff]byte)(unsafe.Pointer(p.p))[:p.n])
  Swig_free(p.p)
  return r
}

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_leveldbwrapperlib_ccc61ccd5094785b(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_leveldbwrapperlib_ccc61ccd5094785b(C.swig_intgo(_swig_i_0)))
	return swig_r
}

type SwigcptrLevelDBInterface uintptr

func (p SwigcptrLevelDBInterface) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrLevelDBInterface) SwigIsLevelDBInterface() {
}

func NewLevelDBInterface() (_swig_ret LevelDBInterface) {
	var swig_r LevelDBInterface
	swig_r = (LevelDBInterface)(SwigcptrLevelDBInterface(C._wrap_new_LevelDBInterface_leveldbwrapperlib_ccc61ccd5094785b()))
	return swig_r
}

func DeleteLevelDBInterface(arg1 LevelDBInterface) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_LevelDBInterface_leveldbwrapperlib_ccc61ccd5094785b(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrLevelDBInterface) Put(arg2 string, arg3 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_LevelDBInterface_Put_leveldbwrapperlib_ccc61ccd5094785b(C.uintptr_t(_swig_i_0), *(*C.swig_type_1)(unsafe.Pointer(&_swig_i_1)), *(*C.swig_type_2)(unsafe.Pointer(&_swig_i_2)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
}

func (arg1 SwigcptrLevelDBInterface) Get(arg2 string) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r_p := C._wrap_LevelDBInterface_Get_leveldbwrapperlib_ccc61ccd5094785b(C.uintptr_t(_swig_i_0), *(*C.swig_type_4)(unsafe.Pointer(&_swig_i_1)))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

type LevelDBInterface interface {
	Swigcptr() uintptr
	SwigIsLevelDBInterface()
	Put(arg2 string, arg3 string)
	Get(arg2 string) (_swig_ret string)
}


